Repository zucchett/ScientificComputingWithPython2023, pull requests merged in 2023-12, with the labels that each got.

#122 ex 04, 05, 06, 07 - Zanirato
  04ex_numpy.ipynb
  05ex_pandas.ipynb
  06ex_dataio.ipynb
  07ex_visualization.ipynb
Labels: question

#107 hw2
  04_numpy.ipynb
  04ex_numpy.ipynb
  04ex_numpy.py
  05_pandas.ipynb
  05ex_pandas.ipynb
  05ex_pandas.py
  06_dataio.ipynb
  06ex_dataio.ipynb
  06ex_dataio.py
  07_visualization.ipynb
  07ex_visualization.ipynb
  07ex_visualization.py
  08_algebra.ipynb
  08ex_algebra.ipynb
  images/Singular-Value-Decomposition.png
  images/data_format.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
Labels: some issues, question

#111 Davide Costa
  ex04.ipynb
  ex05.ipynb
  ex06.ipynb
  ex07.ipynb
  ex08.ipynb
Labels: some issues, question

#112 2nd block of exercises
  04ex_numpy.ipynb
  04ex_numpy.py
  05_pandas.ipynb
  05ex_pandas.ipynb
  05ex_pandas.py
  06_dataio.ipynb
  06ex_dataio.ipynb
  06ex_dataio.py
  07_visualization.ipynb
  07ex_visualization.ipynb
  07ex_visualization.py
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  images/Singular-Value-Decomposition.png
  images/data_format.png
  images/profile.png
  images/two_categories_scatter_plot.png
Labels: some issues, question

#113 Second batch of exercises
  01ex_introduction.py
  02ex_fundamentals.py
  03ex_representation.py
  04ex_numpy (1).ipynb
  04ex_numpy.ipynb
  05ex_pandas (1).ipynb
  05ex_pandas.ipynb
  06ex_dataio (1).ipynb
  06ex_dataio.ipynb
  07ex_visualization (1).ipynb
  07ex_visualization.ipynb
Labels: some issues, question

#115 Assignment 04_05_06_07
  ex04_numpy.ipynb
  ex06_dataio.ipynb
  ex07_visualization.ipynb
  exe05_pandas.ipynb
Labels: invalid, question

#127 HW 4,5,6,7
  02ex_fundamentals.ipynb
  03_representation.ipynb
  03ex_representation.ipynb
  04_numpy.ipynb
  04ex_numpy.ipynb
  04ex_numpy.py
  05_pandas.ipynb
  05ex_pandas.ipynb
  06_dataio.ipynb
  06ex_dataio.ipynb
  07_visualization.ipynb
  07ex_visualization.ipynb
  images/data_format.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
Labels: question

#84 Exercices 4 to 7
  04_numpy.ipynb
  04ex_numpy.ipynb
  05_pandas.ipynb
  05ex_pandas.ipynb
  06_dataio.ipynb
  06ex_dataio.ipynb
  07_visualization.ipynb
  07ex_visualization.ipynb
  images/data_format.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
  python files/01ex_introduction.py
  python files/02ex_fundamentals.py
  python files/03ex_representation.py
  python files/04ex_numpy.py
  python files/05ex_pandas.py
  python files/06ex_dataio.py
  python files/07ex_visualization.py
Labels: question

#117 Naouresatidel hamrouni
  04ex_numpy.ipynb
  05ex_pandas .ipynb
  06ex_OSEMN.ipynb
  07ex_visualization.ipynb
Labels: question

#123 Assignment 04 & 05 & 06 & 07
  04ex_numpy.ipynb
  05ex_pandas.ipynb
  06ex_dataio.ipynb
  07ex_visualization.ipynb
Labels: question
