Repository zucchett/ScientificComputingWithPython2023, pull requests merged in 2024-01, with the labels that each got.

#131 Yekaterina muradyan
  04_numpy.ipynb
  04ex_numpy.ipynb
  05_pandas.ipynb
  05ex_pandas.ipynb
  06_dataio.ipynb
  06ex_dataio.ipynb
  07_visualization.ipynb
  07ex_visualization.ipynb
  08_algebra.ipynb
  08ex_algebra.ipynb
  exercises/04ex_introduction.ipynb
  exercises/05ex_introduction.ipynb
  exercises/06ex_introduction.ipynb
  exercises/07ex_introduction.ipynb
Labels: question

#138 Davide Costa's pull request
  ex08.ipynb
  ex09.ipynb
  ex10.ipynb
  ex11.ipynb
Labels: ok

#139 week8-week11 done
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/Singular-Value-Decomposition.png
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#140 Rikkemelboe nielsen
  08ex_algebra_RN.ipynb
  09ex_numerical_RN.ipynb
  10ex_tests_RN.ipynb
  11ex_montecarlo_RN.ipynb
Labels: ok

#177 third deadline
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#175 F. Zanirato - ex 8-9-10-11
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#174 Ex 8,9,10,11
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#173 last excercises
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#172 Last exercises
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/Singular-Value-Decomposition.png
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#171 Last commit of third section of exercises
  08ex_algebra_2096407.ipynb
  09ex_numerical_2096407.ipynb
  10ex_tests_2096407.ipynb
  11ex_montecarlo_2096407.ipynb
  Consegna/08ex_algebra_2096407.ipynb
  Consegna/09ex_numerical_2096407.ipynb
  Consegna/10ex_tests_2096407.ipynb
  Consegna/11ex_montecarlo_2096407.ipynb
Labels: ok

#170 Exercises 08,09,10,11
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#169 Exercises up to 11ex
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#168 hw3
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#167 Lab 08-09-10-11
  01ex_introduction.py
  02ex_fundamentals.py
  03ex_representation.py
  04ex_numpy.ipynb
  05ex_pandas.ipynb
  06ex_dataio.ipynb
  07ex_visualization.ipynb
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
  README.md
  images/Singular-Value-Decomposition.png
  images/data_format.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
Labels: ok

#166 commit 3
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#165 Final commit
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#164 HW3 (Sina Tavakoli)
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  HW3/08ex_algebra.ipynb
  HW3/09ex_numerical.ipynb
  HW3/10ex_tests.ipynb
  HW3/11ex_montecarlo.ipynb
  images/Singular-Value-Decomposition.png
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#163 Final batch of homeworks
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#162 VinayakDev
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#161 HW Homework 8th - 9th - 10th - 11th Done
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#159 Last Deployment
  ExercisesToUpload/08ex_algebra.ipynb
  ExercisesToUpload/09ex_numerical.ipynb
  ExercisesToUpload/10ex_tests.ipynb
  ExercisesToUpload/11ex_montecarlo.ipynb
Labels: ok

#158 Elnaz d exercise
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#155 Huan
  .gitignore
  08_algebra.ipynb
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok, question

#154 Last series of exercises 08, 09, 10, 11
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#153 Added last set of exercises solutions
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#148 Exercise 08, 09,10 and 11 added.
  08ex_algebra_solution.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  09ex_numerical_solution.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  10ex_tests_solution.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  11ex_montecarlo_solution.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#146 3rd set of exercises
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#145 Branch andrrob scientific
  04_numpy.ipynb
  05_pandas.ipynb
  06_dataio.ipynb
  07_visualization.ipynb
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/Singular-Value-Decomposition.png
  images/data_format.png
  images/moonlanding.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
  images/xkcd_curve_fitting.png
Labels: ok

#144 Andrea dev - 08,09,10,11
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#142 Last hand-in Anna dev
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#141 Fattokh Homework#3
  07ex_visualization.ipynb
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: ok

#143 Solutions up to 11th exercise
  02ex_introduction.py
  04_numpy.ipynb
  04ex_numpy.ipynb
  04ex_numpy.py
  05_pandas.ipynb
  05ex_pandas.ipynb
  05ex_pandas.py
  06_dataio.ipynb
  06ex_dataio.ipynb
  06ex_dataio.py
  07_visualization.ipynb
  07ex_visualization.ipynb
  07ex_visualization.py
  08_algebra.ipynb
  08ex_algebra.ipynb
  08ex_algebra.py
  09_numerical.ipynb
  09ex_numerical.ipynb
  09ex_numerical.py
  10_tests.ipynb
  10ex_tests.ipynb
  10ex_tests.py
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  11ex_montecarlo.py
  images/Singular-Value-Decomposition.png
  images/data_format.png
  images/moonlanding.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
  images/xkcd_curve_fitting.png
Labels: ok

#176 Final homework submission
  09ex_numerical.ipynb
  10ex_tests.ipynb
  8assig_algebra.ipynb
  ex09_numerical.ipynb
  ex11_montecarlo.ipynb
  images/moonlanding.png
  images/xkcd_curve_fitting.png
Labels: ok

#187 HW DELIVERY FATEMEH JAFARI ESKARI
  08ex_algebra.ipynb
  09ex_numerical.ipynb
  10ex_tests.ipynb
  11ex_montecarlo.ipynb
Labels: question

#151 Yekaterina muradyan
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  exercises/08ex_introduction.ipynb
  exercises/09ex_introduction.ipynb
  exercises/10ex_introduction.ipynb
  exercises/11ex_introduction.ipynb
Labels: ok

#150 Last labs: 08, 09, 10, 11
  04_numpy.ipynb
  04ex_numpy.ipynb
  05_pandas.ipynb
  06_dataio.ipynb
  07_visualization.ipynb
  08_algebra.ipynb
  08ex_algebra.ipynb
  09_numerical.ipynb
  09ex_numerical.ipynb
  10_tests.ipynb
  10ex_tests.ipynb
  11_montecarlo.ipynb
  11ex_montecarlo.ipynb
  images/Singular-Value-Decomposition.png
  images/data_format.png
  images/numpy_broadcasting.png
  images/numpy_fancy_indexing.png
  images/numpy_indexing.png
  images/profile.png
  images/two_categories_scatter_plot.png
Labels: ok
